language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
  global:
    - JAVA7_HOME=/usr/lib/jvm/java-8-oracle
    - JAVA8_HOME=/usr/lib/jvm/java-8-oracle

before_install:
  - chmod +x gradlew

script: ./gradlew clean build test

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradle bintrayUpload
  on:
    branch: master

notifications:
  email: false
  slack: brunodles:UcI2SRdgkY9He1ZwJ8tXrECD
